# Database Configuration
spring.application.name=domitila-api
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/domitila_db?useSSL=false&serverTimezone=Atlantic/Canary&allowPublicKeyRetrieval=true&allowLoadLocalInfile=false&allowUrlInLocalInfile=false&allowLoadLocalInfileInPath=/&maxAllowedPacket=655360
spring.datasource.username=root
spring.datasource.password=${MySQL}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Atlantic/Canary

# Jackson (JSON) Time Zone
spring.jackson.time-zone=Atlantic/Canary

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=15m
jwt.refresh-token-name=refresh_token
jwt.refresh-expiration=7d
jwt.issuer=domitila-api
jwt.audience=domitila-frontend


# Email Verification Token
app.email.verification-token-expiration=24h

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${Email_User}
spring.mail.password=${Email_Pass}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Email from address
mail.from=noreply@domitila.com
mail.app-name=Domitila API

# Application Configuration
app.frontend.url=http://localhost
app.backend.url=http://localhost:8080

# Para Produccion:
# app.frontend.url=https://domitila.com
# app.backend.url=https://domitila.com

app.security.allowed-origin-patterns[0]=http://localhost
app.security.allowed-origin-patterns[1]=https://localhost
app.security.allowed-origin-patterns[2]=http://127.0.0.1
app.security.allowed-origin-patterns[3]=https://127.0.0.1

# Habilitar para Producción (poner a true), con https
app.security.cookie.secure=false

app.security.cookie.same-site=Lax
app.security.cookie.path=/
app.security.cookie.access-token-name=auth_token

# File Upload Limits
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Upload Directory Configuration
# Ruta absoluta para garantizar que encuentra las imagenes sin importar desde donde se ejecute
# Si UPLOAD_DIR no está definida, usa la ruta absoluta de prueba
upload.dir=${UPLOAD_DIR:${user.home}/domitila-api/users}

# Logging
logging.level.root=INFO
logging.level.com.asociaciondomitila=INFO
logging.level.org.springframework.security=WARN

# MVC
spring.web.resources.add-mappings=false
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
spring.servlet.encoding.force-request=true
spring.servlet.encoding.force-response=true

# Actuator Health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized