GET http://localhost:8089/api/v1/alumnos

###

GET http://localhost:8089/api/v1/alumnos/en-cursos

###

POST http://localhost:8089/api/v1/alumnos
Content-Type: application/json

{
    "nombre": "César Matelat",
    "email": "cesar@formacion.com",
    "curso_id": 1
}

###

DELETE http://localhost:8089/api/v1/alumnos/3