GET http://localhost:8089/api/v1/cursos

###

GET http://localhost:8089/api/v1/cursos/con-alumnos

###

POST http://localhost:8081/api/v1/cursos
Content-Type: application/json

{
  "titulo": "Electricidad de Obra",
  "modalidad": "Presencial",
  "duracion": 50
}

###

DELETE http://localhost:8089/api/v1/cursos/1