GET http://localhost:8088/api/v1/cursos

###

GET http://localhost:8088/api/v1/cursos/con-alumnos

###

POST http://localhost:8088/api/v1/cursos
Content-Type: application/json

{
  "titulo": "Avanzado de Java",
  "modalidad": "PRESENCIAL",
  "duracion": 45
}