spring.application.name=autolavadomvc
server.port=8085

# Configuración de la conexión a MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/autolavado
spring.datasource.username=root
spring.datasource.password=Anubis@68
# spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.web.resources.static-locations=classpath:/static/,file:frontend/
spring.thymeleaf.check-template-location=false
