name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v6

      - name: Configurar Java 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "25"
          cache: maven

      - name: Compilar y ejecutar tests (Maven Wrapper)
        working-directory: modulo3demo
        run: bash ./mvnw -B -ntp test

      - name: Contruir la APP
        working-directory: modulo3demo
        run: bash ./mvnw package
