name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v5

      - name: Configurar Java 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      # Comando global directo en la máquina virtual de Linux
      - name: Ejecutar pruebas y construir aplicación
        run: mvn clean package