spring.application.name=api_gateway
server.port=8088

# Sincronización limpia con Eureka
spring.cloud.discovery.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Desactiva la caché del balanceador de carga para prevenir errores de mapas internos
spring.cloud.loadbalancer.cache.enabled=false

# ----------------------------------------------------
# CONFIGURACIÓN CORRECTA DE RUTAS (CON ÍNDICES)
# ----------------------------------------------------

# Ruta 0: Socios (Usa guion medio en lb:// ya que Eureka lo convierte internamente)
spring.cloud.gateway.server.webmvc.routes[0].id=socios-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://SOCIOS-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/socios/**

# Ruta 1: Actividades
spring.cloud.gateway.server.webmvc.routes[1].id=actividades-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ACTIVIDADES-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/actividades/**